spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frame-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 12800KB
      max-request-size: 12800KB
storage:
  location: D:\images

#mybatis:
#  type-aliases-package: com.xbcai.model
#  mapperLocations: classpath:mappers/*.xml
#
#  configuration:
#    mapUnderscoreToCamelCase: true
mybatis-plus:
  mapper-locations: classpath:/mappers/**/*.xml
  global-config:
    db-config:
      id-type: auto